[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
build_flags =
    -DWIFI_SSID=\"${sysenv.WIFI_SSID}\"
    -DWIFI_PASS=\"${sysenv.WIFI_PASS}\"

lib_deps =
    adafruit/Adafruit VL53L1X
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library
